
name: WhatsApp-Bot-Run

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Post-Setup Node.js
      run: echo "Node.js setup done"

    - name: Post-Checkout Repo
      run: echo "Checkout completed"

    - name: Install dependencies
      run: npm install

    - name: Run WhatsApp bot
      run: |
        echo "Starting WhatsApp bot..."
        timeout 18000 bash -c 'while true; do npm start || echo "Bot crashed, restarting..."; sleep 5; done'

    - name: Re-Trigger Workflow
      if: always()
      run: |
        curl -X POST \
          -H "Authorization: Bearer secrets.ADDRESS "           -H "Accept: application/vnd.github.v3+json"           https://api.github.com/repos/{{ github.repository }}/actions/workflows/WhatsApp-Bot-Run.yml/dispatches \
          -d '{"ref":"main"}'
